# Generated by Django 4.1.13 on 2024-08-31 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcerp_estoque', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoafisica',
            name='cep',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoafisica',
            name='ponto_referencia',
            field=models.EmailField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoafisica',
            name='rua',
            field=models.EmailField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoajuridica',
            name='cep',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoajuridica',
            name='ponto_referencia',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoajuridica',
            name='rua',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
