# Generated by Django 4.1.13 on 2024-08-31 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcerp_estoque', '0002_pessoafisica_cep_pessoafisica_ponto_referencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoafisica',
            name='ponto_referencia',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='pessoafisica',
            name='rua',
            field=models.CharField(max_length=150),
        ),
    ]
