# Generated by Django 4.1.13 on 2024-09-03 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcerp_estoque', '0003_alter_pessoafisica_ponto_referencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoafisica',
            name='penalizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pessoajuridica',
            name='penalizado',
            field=models.BooleanField(default=False),
        ),
    ]
