# Generated by Django 4.1.13 on 2024-09-13 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcerp_estoque', '0007_produto_estoque_minimo_produto_fornecedor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoafisica',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=10),
        ),
        migrations.AddField(
            model_name='pessoajuridica',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=10),
        ),
    ]
