# Generated by Django 4.1.13 on 2024-10-21 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vcerp_estoque', '0011_alter_profile_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato_pessoa_fisica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11)),
                ('campoendereco', models.CharField(max_length=100)),
                ('campotel', models.CharField(max_length=20)),
                ('campomaterial', models.CharField(max_length=100)),
                ('periodo', models.IntegerField()),
                ('dataentrega', models.DateField()),
                ('datadevolve', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do Pagamento')),
                ('formapagamento', models.CharField(max_length=100, verbose_name='Forma de Pagamento')),
                ('datapagamento', models.DateField()),
                ('funcionario', models.CharField(max_length=100)),
                ('ajudante', models.CharField(max_length=100)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_contratopessoafisica', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
        migrations.CreateModel(
            name='Contrato_empresas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=14)),
                ('campoendereco1', models.CharField(max_length=100)),
                ('campoendereco2', models.CharField(max_length=100)),
                ('campotel1', models.CharField(max_length=20)),
                ('campotel2', models.CharField(max_length=20)),
                ('campomaterial', models.CharField(max_length=100)),
                ('periodo', models.IntegerField()),
                ('dataentrega', models.DateField()),
                ('datadevolve', models.DateField()),
                ('finalizado', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_contratoempresas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
    ]
