# Generated by Django 4.1.13 on 2024-10-21 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vcerp_estoque', '0012_contrato_pessoa_fisica_contrato_empresas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contrato_empresas',
            old_name='nome',
            new_name='razao_social',
        ),
    ]
