# Generated by Django 4.1.13 on 2024-09-16 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vcerp_caixa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caixa',
            name='aberto_em',
        ),
        migrations.RemoveField(
            model_name='caixa',
            name='fechado_em',
        ),
        migrations.AddField(
            model_name='caixa',
            name='numero',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='caixa',
            name='status',
            field=models.CharField(choices=[('disponível', 'Disponível'), ('ocupado', 'Ocupado')], max_length=10),
        ),
        migrations.AlterField(
            model_name='caixa',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caixas', to=settings.AUTH_USER_MODEL),
        ),
    ]
