# Generated by Django 4.1.13 on 2024-09-18 22:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vcerp_caixa', '0002_remove_caixa_aberto_em_remove_caixa_fechado_em_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixa',
            name='status',
            field=models.CharField(choices=[('disponivel', 'Disponível'), ('ocupado', 'Ocupado'), ('fechado', 'Fechado')], max_length=10),
        ),
        migrations.AlterField(
            model_name='caixa',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
