# Generated by Django 4.1.13 on 2024-09-19 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vcerp_caixa', '0004_caixa_data_abertura_caixa_data_fechamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaixaLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('abertura', 'Abertura'), ('fechamento', 'Fechamento')], max_length=10)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('caixa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vcerp_caixa.caixa')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
